#!/bin/sh -e

case "$1" in
    configure|reconfigure)
		ln --symbolic /opt/robo3t/bin/robo3t /usr/bin/robo3t
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
