#!/bin/sh -e

case "$1" in
    remove|purge)
		rm -rf /usr/bin/robo3t
    ;;

    disappear|upgrade|failed-upgrade|abort-install|abort-upgrade)
    ;;

    *) echo "$0: didn't understand being called with \`$1'" 1>&2
    ;;
esac

exit 0
